# Generated by Django 4.0.1 on 2022-04-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passWord', models.CharField(max_length=15)),
                ('studyCategory', models.CharField(max_length=20)),
                ('loginTime', models.DateField()),
                ('weeklyPoints', models.IntegerField(default=0)),
                ('totalPoints', models.IntegerField(default=0)),
                ('goalToday', models.IntegerField(default=0)),
                ('goalWeek', models.IntegerField(default=0)),
                ('completedToday', models.IntegerField(default=0)),
                ('completedWeek', models.IntegerField(default=0)),
                ('plan_Monday', models.IntegerField(default=0)),
                ('plan_Tuesday', models.IntegerField(default=0)),
                ('plan_Wednesday', models.IntegerField(default=0)),
                ('plan_Thursday', models.IntegerField(default=0)),
                ('plan_Friday', models.IntegerField(default=0)),
                ('plan_Saturday', models.IntegerField(default=0)),
                ('plan_Sunday', models.IntegerField(default=0)),
                ('classRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='studyCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studycategory'),
        ),
    ]
