# Generated by Django 4.0.1 on 2022-04-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totalPoints',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='weeklyPoints',
            field=models.IntegerField(default=30),
        ),
    ]
