# Generated by Django 3.0.8 on 2022-04-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_totalpoints_alter_user_weeklypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='maxPeople',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classroom',
            name='passWord',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studycategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
