# Generated by Django 3.0.8 on 2022-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220422_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='passWord',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
