# Generated by Django 3.0.8 on 2022-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220422_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='curPeople',
            field=models.IntegerField(default=1),
        ),
    ]
